### ISSUE TITLE
Invalid registration attempt for an Ore Dictionary item

### ISSUE THREAD

**Issue by scrouthtv** [RythenGlyth/BigMachines#1]
```
[07:07:20] [Client thread/WARN] [FML]: ****************************************
[07:07:20] [Client thread/WARN] [FML]: * Invalid registration attempt for an Ore Dictionary item with name blockAluminium has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[07:07:20] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:665)
[07:07:20] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:651)
[07:07:20] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:650)
[07:07:20] [Client thread/WARN] [FML]: *  at de.bigmachines.blocks.BlockBaseOreDict.postRegister(BlockBaseOreDict.java:19)
[07:07:20] [Client thread/WARN] [FML]: *  at de.bigmachines.init.ModBlocks.lambda$1(ModBlocks.java:40)
[07:07:20] [Client thread/WARN] [FML]: *  at java.util.ArrayList.forEach(ArrayList.java:1257)...
[07:07:20] [Client thread/WARN] [FML]: ****************************************
```

**Comment by scrouthtv** [comment]
![image](https://user-images.githubusercontent.com/23227405/82538479-19269480-9b4c-11ea-8374-48ee4a4b848d.png)
Works for now even tho there is a warning:
![image](https://user-images.githubusercontent.com/23227405/82539262-78d16f80-9b4d-11ea-9de1-20305e7ab9ad.png)

**Comment by scrouthtv** [comment]
143f9d4
closing

**Comment by scrouthtv** [comment]
Blocks don't work

**Comment by scrouthtv** [comment]
9953000
Blocks are first registered, items afterwards.
We try to register the OreDict on the block before its item is registered.
